### ISSUE TITLE
OpenAPI router unsafe assignment with `fromHono`

### ISSUE THREAD

**Issue by kylecarhart** [cloudflare/chanfana#183]
I am getting a typescript error when trying to use either `fromHono`.

```
Unsafe assignment of an `any` value.eslint[@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)
```

I took a look at the types and saw this:

```typescript
// src/adapters/hono.ts
export function fromHono<M>(
  router: M,
  options?: RouterOptions
): M & OpenAPIRouterType<M> & any {
  const openapiRouter = new HonoOpenAPIHandler(router, options)

  return new Proxy(router, {
    // ...
  }
}
```

Whats the reasoning for the `any` at the end of the return type? Same thing for `fromIttyRouter` as well... I'd have to disable a bunch of eslint rules for this file to get it working, but then I am losing all my type safety that I had before v2.

**Comment by alexanderatallah** [comment]
Seeing this as well - seems like a bug?

**Comment by louisgv** [comment]
It's been an issue since 2.0.0: 

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/02936e9a-d5ed-4562-9ee9-8a15424ad7a5">

The older package's typing (itty-router-openapi) seems a bit more strict :-?

**Comment by G4brym** [comment]
Hey there, I've just published a new release (v2.1.0) that removes the any from the adapters, can you confirm the issue is fixed?

**Comment by louisgv** [comment]
@G4brym - it seems the middleware registration typing is still wrong, I can't register middleware: 
<img width="832" alt="image" src="https://github.com/user-attachments/assets/6146d631-ecb6-48fe-b681-0cac53102de5">

**Comment by louisgv** [comment]
The typing when grabbing the API for hono test is wrong with the testClient helper: 
<img width="659" alt="image" src="https://github.com/user-attachments/assets/4e37e91c-1da5-4d13-bb31-b5a2408ce864">

**Comment by kylecarhart** [comment]
Honestly, I just went ahead and migrated away from itty-router and went straight to Hono with Zod OpenAPI Hono. Was able to reuse a lot of our existing code, just had to change the class based routes to the Hono way; no longer depending on Chanfana.
